import Foundation

/// A local UI preference, independent of display configuration and the v2 protocol.
enum AppLanguage: String, CaseIterable {
    case system = "system"
    case simplifiedChinese = "zh-Hans"
    case english = "en"

    static func resolve(_ preference: AppLanguage, preferredLanguages: [String]) -> AppLanguage {
        guard preference == .system else { return preference }
        let primary = preferredLanguages.first?.lowercased() ?? "en"
        return primary == "zh" || primary.hasPrefix("zh-") ? .simplifiedChinese : .english
    }
}

enum L10n {
    static let preferenceKey = "App.UILanguage"
    static var preference: AppLanguage {
        get { AppLanguage(rawValue: UserDefaults.standard.string(forKey: preferenceKey) ?? "system") ?? .system }
        set { UserDefaults.standard.set(newValue.rawValue, forKey: preferenceKey) }
    }
    static var language: AppLanguage {
        AppLanguage.resolve(preference, preferredLanguages: Locale.preferredLanguages)
    }

    static func text(_ source: String, language: AppLanguage? = nil) -> String {
        (language ?? self.language) == .english ? english[source] ?? source : source
    }

    static func format(_ source: String, _ arguments: String...) -> String {
        render(text(source), arguments: arguments)
    }

    /// Parse the template once; inserted user text is never interpreted or replaced.
    static func render(_ template: String, arguments: [String]) -> String {
        var output = ""
        var cursor = template.startIndex
        while cursor < template.endIndex {
            if template[cursor] == "{",
               let end = template[cursor...].firstIndex(of: "}"),
               let index = Int(template[template.index(after: cursor)..<end]),
               arguments.indices.contains(index) {
                output += arguments[index]
                cursor = template.index(after: end)
            } else {
                output.append(template[cursor])
                cursor = template.index(after: cursor)
            }
        }
        return output
    }

    static let english: [String: String] = [
        "取消申请": "Cancel Request",
        "已启用登录启动。": "Launch at login is enabled.",
        "登录启动未启用。": "Launch at login is disabled.",
        "等待系统批准。请在系统设置 → 通用 → 登录项中允许 SFlip。": "Approval required. Allow SFlip in System Settings → General → Login Items.",
        "系统尚未找到登录项。请将 SFlip 放入“应用程序”后重新开启。": "The system has not found the login item. Move SFlip to Applications and enable it again.",
        "打开系统登录项设置": "Open Login Items Settings",
        "登录启动服务不可用。": "The launch at login service is unavailable.",
        "系统未启用登录启动，请检查应用程序位置和系统登录项设置。": "The system did not enable launch at login. Check the app location and Login Items settings.",
        "系统未关闭登录启动，请检查系统登录项设置。": "The system did not disable launch at login. Check Login Items settings.",
        "亮度": "Brightness",
        "对比度": "Contrast",
        "输入源": "Input Source",
        "音量": "Volume",
        "当前连接不支持可靠读取": "Reliable reading is unavailable on this connection",
        "没有可用的硬件 DDC 后端。": "No hardware DDC backend is available.",
        "目标显示器在当前 DDC 后端中不可用。": "The target display is unavailable in the current DDC backend.",
        "读取{0}失败。": "Failed to read {0}.",
        "写入{0}失败。": "Failed to write {0}.",
        "{0}数值超出安全范围：{1}。": "{0} value is outside the safe range: {1}.",
        "读取{0}失败：{1}。": "Failed to read {0}: {1}.",
        "当前连接不支持可靠读取。": "Reliable reading is unavailable on this connection.",
        "DDC 操作已取消。": "DDC operation cancelled.",
        "读取请求写入失败": "Failed to send the read request",
        "读取回复超时": "Read response timed out",
        "读取回复 I2C 失败": "Read response I2C failure",
        "显示器返回 DDC 空回复": "Display returned an empty DDC response",
        "回复长度无效": "Invalid response length",
        "回复校验失败": "Response checksum failed",
        "回复来源无效": "Invalid response source",
        "回复载荷长度无效": "Invalid response payload length",
        "回复类型不匹配": "Response type mismatch",
        "显示器拒绝该 VCP 请求": "Display rejected this VCP request",
        "回复的 VCP 项不匹配": "Response VCP code mismatch",
        "回复的 VCP 数值范围无效": "Invalid response VCP value range",
        "连续严格回复的 VCP 数值不一致": "Consecutive strict responses contain inconsistent VCP values",
        "外接显示器": "External Display",
        "未开启可读取的 DDC 功能": "No readable DDC controls are enabled",
        "Apple Silicon 原生 DDC": "Apple Silicon Native DDC",
        "Intel Mac 不支持 Apple Silicon 原生 DDC": "Apple Silicon Native DDC is unsupported on Intel Mac",
        "Apple Silicon 原生 DDC 没有返回可用的外接显示器。": "Apple Silicon Native DDC returned no available external displays.",
        "DDC 数值超出有效范围：{0}": "DDC value is outside the valid range: {0}",
        "{0} 尚未配置输入源，未执行切屏。": "{0} has no input source configured; no switch was performed.",
        "原生 DDC 写入失败：VCP 0x{0} = {1}。": "Native DDC write failed: VCP 0x{0} = {1}.",
        "显示器配置数据已损坏或格式不完整。": "Display configuration data is damaged or incomplete.",
        "显示器配置版本 {0} 不受当前 App 支持。": "Display configuration version {0} is unsupported by this app.",
        "无法编码本机配置。": "Unable to encode local configuration.",
        "无法安全写入本机配置。": "Unable to safely write local configuration.",
        "上次配置迁移或保存失败，需要用户检查。": "The previous configuration migration or save failed; review is required.",
        "配置包含重复标识、重复名称或非法字段。": "Configuration contains duplicate identifiers, duplicate names, or invalid fields.",
        "请填写配置名称。": "Enter a configuration name.",
        "请填写对端地址。": "Enter the peer address.",
        "通信端口必须在 1–65535 之间。": "The communication port must be between 1 and 65535.",
        "配对码必须为 8–128 个 UTF-8 字节。": "The pairing code must contain 8–128 UTF-8 bytes.",
        "请至少为一台显示器填写 1–65535 的对端输入源。": "Set a peer input source between 1 and 65535 for at least one display.",
        "存在不再对应当前显示器的旧输入源映射，请重新保存配置。": "Some saved input mappings no longer match a display; save the configuration again.",
        "显示器 {0}": "Display {0}",
        "本机": "Local",
        "配置 1": "Configuration 1",
        "未启用": "Disabled",
        "配置不完整": "Configuration Incomplete",
        "正在连接": "Connecting",
        "正在检测": "Checking",
        "无响应": "No Response",
        "配对码不匹配": "Pairing Code Mismatch",
        "监听失败（系统码：{0}）": "Listener Failed (system code: {0})",
        "发送失败（系统码：{0}）": "Send Failed (system code: {0})",
        "已连接": "Connected",
        "连接已断开": "Disconnected",
        "已和对端建立连接": "Connected to Peer",
        "已和对端（{0}）建立连接": "Connected to {0}",
        "USB 切换已开启": "USB Switching On",
        "USB 切换已关闭": "USB Switching Off",
        "混合": "Mixed",
        "未知": "Unknown",
        "约 {0}": "Approx. {0}",
        "对端输入源": "Peer Input Source",
        "即时保存状态": "Save Status",
        "已保存": "Saved",
        "保存失败，已恢复": "Save Failed, Restored",
        "配置保存状态": "Configuration Save Status",
        "USB 配置保存状态": "USB Configuration Save Status",
        "协同配置保存状态": "Collaboration Configuration Save Status",
        "常规": "General",
        "USB 切换": "USB Switching",
        "协同": "Collaboration",
        "显示器": "Displays",
        "诊断": "Diagnostics",
        "关于": "About",
        "自动切换": "Automatic Switching",
        "联动协同": "Collaboration Wake",
        "协同状态": "Collaboration Status",
        "配置": "Configuration",
        "触发设备": "Trigger Device",
        "当前状态": "Current Status",
        "尚未检测到显示器": "No Displays Detected",
        "联动目标": "Wake Target",
        "当前配置": "Current Configuration",
        "添加配置": "Add Configuration",
        "配置名称": "Configuration Name",
        "启用此配置": "Enable This Configuration",
        "对端地址": "Peer Address",
        "端口": "Port",
        "配对密码": "Pairing Code",
        "本机触发设备": "Local Trigger Device",
        "删除配置": "Delete Configuration",
        "检查网络权限": "Check Network Permission",
        "检测连接": "Detect Connection",
        "输入源切换已被安全门控阻止。": "Input source switching was blocked by the safety gate.",
        "目标显示器未配置输入源。": "No input source is configured for the target display.",
        "输入源数值超出有效范围：{0}": "Input source value is outside the valid range: {0}",
        "目标显示器的原生 DDC 通道当前不可用。": "The target display's native DDC channel is currently unavailable.",
        "写入显示器输入源失败。": "Failed to write the display input source.",
        "诊断状态暂不可用。": "Diagnostic status is temporarily unavailable.",
        "设置…": "Settings…",
        "设置": "Settings",
        "退出": "Quit",
        "显示器调节失败": "Display Adjustment Failed",
        "已收到按键，正在读取显示器当前值": "Key received; reading the current display value",
        "显示器控制": "Display Controls",
        "对端不可用，未执行切换": "Peer unavailable; no switch performed",
        "请检查对端连接后重试。": "Check the peer connection and try again.",
        "协同配置尚未连接": "Collaboration Configuration Is Not Connected",
        "应用会自动连接；请检查地址、端口和配对码。": "The app connects automatically; check the address, port, and pairing code.",
        "部分切换失败": "Some Switches Failed",
        "显示器输入源切换失败": "Display Input Source Switch Failed",
        "切换完成": "Switch Complete",
        "配置安全模式已启用": "Configuration Safety Mode Enabled",
        "显示器配置保存失败": "Failed to Save Display Configuration",
        "显示器检测失败": "Display Detection Failed",
        "已收到系统媒体按键": "System media key received",
        "当前音频输出由 macOS 处理，未执行 DDC": "macOS handles the current audio output; no DDC performed",
        "安全状态阻止写入": "Safety state blocked the write",
        "物理显示器拓扑尚未可信确认": "Physical display topology is not yet confirmed",
        "当前没有可信可读取的物理显示器": "No trusted readable physical display is available",
        "按键重复过多，已拒绝本次事件": "Too many repeated keys; event rejected",
        "媒体按键队列已满，已拒绝本次事件": "Media key queue is full; event rejected",
        "DDC 操作当前不可用": "DDC operation is currently unavailable",
        "配置或显示器拓扑已变化，已取消": "Configuration or display topology changed; cancelled",
        "配置安全模式：网络交接已停用": "Configuration Safety Mode: Network Handover Disabled",
        "统一": "Linked",
        "部分显示器未配置 USB 目标输入源，已安全跳过": "Some displays have no USB target input source and were safely skipped",
        "部分显示器当前不可用": "Some displays are currently unavailable",
        "部分显示器切换失败": "Some display switches failed",
        "本机切换已继续，协同唤醒未发送": "Local switching continued; collaboration wake was not sent",
        "未检测到已认证目标，请从菜单手动选择配置": "No authenticated target detected; select a configuration from the menu",
        "DDC 音量": "DDC Volume",
        "已提交 {0} / {1}（{2}%）": "Submitted {0} / {1} ({2}%)",
        "已提交到 {0} 台显示器（{1}%–{2}%）": "Submitted to {0} displays ({1}%–{2}%)",
        "当前读取 {0} / {1}（{2}%）": "Current reading {0} / {1} ({2}%)",
        "当前读取 {0} 台显示器（{1}%–{2}%）": "Current readings for {0} displays ({1}%–{2}%)",
        "显示器写入失败；下一次按键将交给 macOS": "Display write failed; the next key will go to macOS",
        "DDC 音量状态": "DDC Volume Status",
        "DDC 音量写入失败": "DDC Volume Write Failed",
        "已向 {0} 台显示器提交": "Submitted to {0} displays",
        "已忽略静音长按重复": "Ignored repeated mute hold",
        "没有启用对应控制项的显示器": "No display has the corresponding control enabled",
        "缺少可信当前值，未写入": "No trusted current value; nothing written",
        "联动值不一致，未写入": "Linked values differ; nothing written",
        "没有可安全恢复的音量，未写入": "No safely restorable volume; nothing written",
        "已达到调节边界，未写入": "Adjustment limit reached; nothing written",
        " 最近一次：{0}。": " Last action: {0}.",
        "媒体快捷键关联已启用": "Media Key Shortcuts Enabled",
        "F1/F2 始终放行；符合安全条件时接管 F10/F11/F12。{0}": "F1/F2 always pass through; F10/F11/F12 are intercepted when safe.{0}",
        "F1/F2 关联亮度，F10/F11/F12 关联音量；系统原生行为不受影响。{0}": "F1/F2 control brightness and F10/F11/F12 control volume; native system behavior is preserved.{0}",
        "媒体快捷键关联需要输入监控权限": "Media Key Shortcuts Need Input Monitoring Permission",
        "未授权时仅停用快捷键关联，其他功能不受影响。请在“系统设置 > 隐私与安全性 > 输入监控”中允许 SFlip。": "Only media key shortcuts are disabled without permission. Allow SFlip in System Settings > Privacy & Security > Input Monitoring.",
        "申请权限": "Request Permission",
        "媒体快捷键监听未启动": "Media Key Monitoring Not Started",
        "未执行任何快捷键 DDC 写入；可重试监听，其他功能不受影响。": "No shortcut DDC writes were performed. Retry monitoring; other features remain available.",
        "重试": "Retry",
        "HDMI/DP DDC 音量接管（可选）": "HDMI/DP DDC Volume Takeover (Optional)",
        "默认关闭。需要辅助功能权限；仅在默认音频输出为 HDMI/DisplayPort，且 macOS 自身无法调音量时接管 F10/F11/F12。": "Off by default. Requires Accessibility permission. Intercepts F10/F11/F12 only when the default audio output is HDMI/DisplayPort and macOS cannot adjust its volume.",
        "音量接管需要辅助功能权限": "Volume Takeover Needs Accessibility Permission",
        "未授权时保持被动监听，不吞按键；仅当输出符合 HDMI/DP 条件时仍额外执行 DDC。可在系统设置中允许 SFlip。": "Without permission, keys pass through with passive monitoring. DDC also runs only for eligible HDMI/DP outputs. Allow SFlip in System Settings.",
        "申请辅助功能权限": "Request Accessibility Permission",
        "主动监听": "Active Monitoring",
        "被动监听": "Passive Monitoring",
        "默认音频输出不可确认": "Default audio output cannot be confirmed",
        "默认音频输出不是 HDMI/DisplayPort": "Default audio output is not HDMI/DisplayPort",
        "macOS 可直接调节当前输出": "macOS can adjust the current output directly",
        "HDMI/DisplayPort 输出符合接管条件": "HDMI/DisplayPort output is eligible for takeover",
        "音量键已接管，每次写入前仍会重新读取显示器": "Volume keys are intercepted; the display is read again before every write",
        "首次按键仍交给 macOS，DDC 成功后再接管": "The first key goes to macOS; takeover starts after DDC succeeds",
        "当前音量键完全交给 macOS，不执行 DDC": "Volume keys go entirely to macOS; no DDC performed",
        "HDMI/DP DDC 音量接管已就绪": "HDMI/DP DDC Volume Takeover Ready",
        "HDMI/DP DDC 音量接管待确认": "HDMI/DP DDC Volume Takeover Pending",
        "Apple Silicon 原生 DDC 在 Intel Mac 上不可用": "Apple Silicon Native DDC is unavailable on Intel Mac",
        "通信端口无效：{0}": "Invalid communication port: {0}",
        "UDP 发送失败：网络监听尚未启动": "UDP send failed: network listener has not started",
        "UDP {0}失败（系统错误 {1}）": "UDP {0} failed (system error {1})",
        "UDP 目标地址解析失败（系统错误 {0}）": "UDP target address resolution failed (system error {0})",
        "创建": "creation",
        "绑定": "binding",
        "发送": "send",
        "接收": "receive",
        "UDP 接收失败": "UDP Receive Failed",
        "UDP 监听失败": "UDP Listener Failed",
        "UDP 回复失败": "UDP Reply Failed",
        "UDP 发送失败": "UDP Send Failed",
        "未检测": "Not Checked",
        "协同连接正常": "Collaboration Connection Working",
        "系统明确拒绝": "System Explicitly Denied Access",
        "请前往“系统设置 → 隐私与安全性 → 本地网络”，允许 SFlip 访问。": "Allow SFlip in System Settings → Privacy & Security → Local Network.",
        "连接失败，请检查权限、地址和防火墙": "Connection failed; check permission, address, and firewall",
        "一款在 macOS 与 Windows 之间协同切换显示器和 USB 设备的原生菜单栏工具。": "A native menu bar tool for switching displays and USB devices between macOS and Windows.",
        "版本 {0} ({1})": "Version {0} ({1})",
        "macOS · {0} · 协议 v2": "macOS · {0} · Protocol v2",
        "未知架构": "Unknown Architecture",
        "读取失败": "Read Failed",
        "读取成功": "Read Successful",
        "写入成功": "Write Successful",
        "已取消": "Cancelled",
        "写入失败": "Write Failed",
        "切换到 {0}": "Switch to {0}",
        "留空或 1–65535": "Empty or 1–65535",
        "{0}输入源": "{0} Input Source",
        "已选择": "Selected",
        "未选择": "Not Selected",
        "协同未启用": "Collaboration Disabled",
        "检测/刷新": "Detect Displays",
        "刷新预览": "Refresh Preview",
        "复制诊断": "Copy Diagnostics",
        "未选择触发设备": "No Trigger Device Selected",
        "USB 切换未启用": "USB Switching Disabled",
        "尚未检测到显示器。": "No displays detected.",
        "未引用本机触发设备": "No local trigger device referenced",
        "学习": "Learn",
        "读取 DDC 参数": "Read DDC Parameters",
        "配置安全模式": "Configuration Safety Mode",
        "{0}\n\n原配置已保留。请检查当前设置并成功保存；在此之前 App 不会执行 USB、DDC、显示器唤醒或网络交接。": "{0}\n\nThe original configuration is preserved. Review and successfully save the current settings. Until then, the app will not perform USB, DDC, display wake, or network handover operations.",
        "设置错误": "Settings Error",
        "登录时启动": "Launch at Login",
        "登录 macOS 后自动在菜单栏启动显示器控制。": "Start display controls in the menu bar when you log in to macOS.",
        "详细诊断记录": "Detailed Diagnostic Recording",
        "默认关闭。仅在排查问题时开启；关闭会清空本次会话的详细记录。": "Off by default. Enable only for troubleshooting. Turning it off clears detailed records from this session.",
        "只监听明确选择的一个本机设备；USB 离开时切换显示器，接入时只唤醒本机；联动协同默认关闭。": "Monitors one explicitly selected local device. USB departure switches displays; arrival only wakes this Mac. Collaboration wake is off by default.",
        "IP 或主机名，例如 peer.example": "IP or hostname, e.g. peer.example",
        "两端填写相同的配对密码": "Use the same pairing code on both devices",
        "协同配置": "Collaboration Configuration",
        "通信端口": "Communication Port",
        "添加协同配置": "Add Collaboration Configuration",
        "删除协同配置": "Delete Collaboration Configuration",
        "检测当前协同配置": "Detect Current Collaboration Configuration",
        "检查本地网络权限": "Check Local Network Permission",
        "申请媒体快捷键输入监控权限": "Request Media Key Input Monitoring Permission",
        "学习 USB 设备": "Learn USB Device",
        "USB 联动目标": "USB Wake Target",
        "根据一个本机 USB 设备的接入状态执行本机显示器动作。": "Performs local display actions based on one local USB device's presence.",
        "检测并刷新显示器": "Detect and Refresh Displays",
        "打开此页面后生成脱敏预览。详细记录默认关闭。": "An anonymized preview is generated when this page opens. Detailed recording is off by default.",
        "诊断预览": "Diagnostic Preview",
        "需要详细轨迹时，请先在“常规”中开启记录并复现问题。": "For detailed traces, enable recording in General and reproduce the issue first.",
        "诊断与隐私": "Diagnostics and Privacy",
        "打开 GitHub": "Open GitHub",
        "MIT 许可证": "MIT License",
        "第三方说明": "Third-Party Notices",
        "离线（已由连续两次可信检测确认）": "Offline (confirmed by two consecutive trusted detections)",
        "删除": "Delete",
        "删除离线显示器{0}": "Delete offline display {0}",
        "尚未检测到显示器，请使用上方的检测按钮。": "No displays detected. Use the detection button above.",
        "联动调节所有显示器": "Link All Displays",
        "只联动同时开启相同控制项的显示器。": "Links only displays with the same controls enabled.",
        "媒体快捷键": "Media Key Shortcuts",
        "媒体快捷键与输入监控权限": "Media Key Shortcuts and Input Monitoring Permission",
        "DDC 音量接管": "DDC Volume Takeover",
        "HDMI/DisplayPort DDC 音量接管与辅助功能权限": "HDMI/DisplayPort DDC Volume Takeover and Accessibility Permission",
        "读取{0} DDC 参数": "Read {0} DDC Parameters",
        "尚未读取": "Not Yet Read",
        "功能": "Control",
        "在托盘显示": "Show in Tray",
        "数值": "Value",
        "{0}功能": "{0} Control",
        "{0}在托盘显示": "{0} Show in Tray",
        "{0}数值": "{0} Value",
        "统一{0}": "Linked {0}",
        "统一{0}{1}": "Linked {0} {1}",
        "部分开启": "Mixed",
        "开启": "On",
        "关闭": "Off",
        "请选择一个已开启、完整且已建立连接的协同配置。": "Select an enabled, complete, connected collaboration configuration.",
        "请先学习一个 USB 设备，并至少配置一台显示器的目标输入源。": "Learn a USB device and configure a target input source for at least one display first.",
        "登录启动设置失败：\n{0}\n\n请确认 App 已放入“应用程序”文件夹。": "Launch at login setup failed:\n{0}\n\nMake sure the app is in the Applications folder.",
        "正在应用": "Applying",
        "正在读取": "Reading",
        "当前无法读取": "Reading Unavailable",
        "删除离线显示器“{0}”？": "Delete offline display “{0}”?",
        "将移除此显示器配置、USB 映射、所有协同映射，以及仅属于该显示器的 DDC 缓存和托盘偏好。此操作不会执行 DDC、USB、网络、唤醒或输入源切换。": "Removes this display's configuration, USB mapping, all collaboration mappings, and its DDC cache and tray preferences. This performs no DDC, USB, network, wake, or input source operations.",
        "取消": "Cancel",
        "对端输入源可留空，填写时必须为 1–65535；0 不会保存或写入显示器。": "Peer input sources may be empty; entered values must be 1–65535. Zero is never saved or written to a display.",
        "配置不完整，已自动停用并保存当前输入。请补全所有字段后重新启用。": "Configuration incomplete; automatically disabled and current input saved. Complete all fields before enabling it again.",
        "设置未保存，已恢复最后有效值：\n{0}": "Settings were not saved; last valid values restored:\n{0}",
        "设置未保存，已恢复最后有效值。": "Settings were not saved; last valid values restored.",
        "已复制当前预览": "Current Preview Copied",
        "等待设备状态": "Waiting for Device Status",
        "需要 macOS 13 或更高版本": "Requires macOS 13 or Later",
        "已引用 {0} 个本机触发设备": "References {0} local trigger devices",
        "配置 {0}": "Configuration {0}",
        "删除协同配置？": "Delete Collaboration Configuration?",
        "此操作会取消该配置尚未完成的本机操作。": "This cancels unfinished local operations for this configuration.",
        "本机配置需要检查": "Local Configuration Needs Review",
        "正在检测 {0}…": "Detecting {0}…",
        "{0}：配对码不匹配": "{0}: Pairing Code Mismatch",
        "{0}：无响应": "{0}: No Response",
        "{0}：监听失败（系统码：{1}）": "{0}: Listener Failed (system code: {1})",
        "{0}：发送失败（系统码：{1}）": "{0}: Send Failed (system code: {1})",
        "等待 USB 变化，请按一次切换器…": "Waiting for USB change; press the switcher once…",
        "选择 USB 触发设备": "Select USB Trigger Device",
        "以下设备在切换动作中发生了变化。请选择一个稳定存在于键鼠链路上的设备。": "These devices changed during switching. Choose one that remains stable in the keyboard and mouse connection.",
        "使用此设备": "Use This Device",
        "USB 设备": "USB Device",
        "语言": "Language",
        "跟随系统": "System",
    ]
}
